export const generos = [
    'Ação e aventura',
    'Ficção afro-americana',
    'Antologias',
    'Infantil',
    'Ficção Cristã',
    'Clássicos',
    'Quadrinhos e romances gráficos',
    'Chegando à maioridade',
    'Ficção Contemporânea',
    'Cultural e étnico',
    'Fantasia',
    'Ficção histórica',
    'Humor e comédia',
    'LGBTQ',
    'Ficção Literária',
    'Mistério e crime',
    'Peças e roteiros',
    'Poesia',
    'Romance',
    'Ficção científica',
    'Contos',
    'Temáticas e motivações',
    'Thriller e Suspense',
    'Autoajuda e autoaprimoramento',
    'Sexo e Relacionamentos',
    'Esportes e atividades ao ar livre',
    'Tecnologia',
    'Escrita e Publicação',
]